### ISSUE TITLE
Пол НИПов

### ISSUE THREAD

**Issue by FTNonsense** [Lichery/Server_Translation_issues#1]
Думаю, что тут уже все понятно. Кондуктор бывает и женщина и мужчина, если в аддоне не реализовать разделение полов, то пусть наставники, ученики все же будут в "мужском", то касается и хозяинов дирижаблей, у которых в оригинальной английской версии нет приставок "Дуротара" или "Тернистой долины", а есть просто "Хозяин дирижабля".
![_kxwdy1bv6s](https://user-images.githubusercontent.com/29949340/27993288-9ea28858-64b8-11e7-8ca8-37781ef06a47.jpg)

**Comment by FTNonsense** [comment]
![08orpm2ta7o](https://user-images.githubusercontent.com/29949340/27993290-bd1bd6cc-64b8-11e7-846b-bd51ea6f2398.jpg)

**Comment by FTNonsense** [comment]
![x7wrk9b3kfm](https://user-images.githubusercontent.com/29949340/27993399-400cc990-64bb-11e7-8967-564a93589db7.jpg)

**Comment by FTNonsense** [comment]
![1](https://user-images.githubusercontent.com/29949340/27993472-c452d856-64bc-11e7-861e-e127f95b3811.jpg)
![08orpm2ta7o](https://user-images.githubusercontent.com/29949340/27993473-c454ec86-64bc-11e7-8fe5-a23879682141.jpg)

**Comment by Lichery** [comment]
поправил
