### ISSUE TITLE
Гордо

### ISSUE THREAD

**Issue by FTNonsense** [Lichery/Server_Translation_issues#23]
![j_8p2y5ureq](https://user-images.githubusercontent.com/29949340/27993533-b1518ee0-64bd-11e7-8b76-e90de4c7ee31.jpg)
Отсутствует перевод некоторых фраз

**Comment by Lichery** [comment]
переводит

**Comment by FTNonsense** [comment]
Все реплики кроме этой переведены, только что проверил

**Comment by FTNonsense** [comment]
работает
