### ISSUE TITLE
Непереведенные НИПы у Зала СЛавы в Оргриммаре

### ISSUE THREAD

**Issue by FTNonsense** [Lichery/Server_Translation_issues#32]
![1](https://user-images.githubusercontent.com/29949340/28023880-379f9c02-65a0-11e7-9aeb-6920e266be73.jpg)
![11](https://user-images.githubusercontent.com/29949340/28023881-37ab5a38-65a0-11e7-97e6-4f5dd68a4126.jpg)

**Comment by FTNonsense** [comment]
![1](https://user-images.githubusercontent.com/29949340/28023912-4e58bdca-65a0-11e7-97b1-d3926af2e45c.jpg)
![11](https://user-images.githubusercontent.com/29949340/28023914-4e8bed3a-65a0-11e7-827a-160229ed313f.jpg)

**Comment by FTNonsense** [comment]
![1](https://user-images.githubusercontent.com/29949340/28023946-68e8b316-65a0-11e7-82ff-5c7ccb7e814b.jpg)
![11](https://user-images.githubusercontent.com/29949340/28023947-6915d3be-65a0-11e7-955f-b22513bf6992.jpg)

**Comment by FTNonsense** [comment]
![wow 2017-07-10 14-15-46-558](https://user-images.githubusercontent.com/29949340/28023974-7c3007f8-65a0-11e7-980b-490128cdc629.jpg)

**Comment by FTNonsense** [comment]
![wow 2017-07-10 14-15-49-157](https://user-images.githubusercontent.com/29949340/28023987-8ab049d2-65a0-11e7-9b21-bca416efa252.jpg)

**Comment by FTNonsense** [comment]
![wow 2017-07-10 14-15-51-941](https://user-images.githubusercontent.com/29949340/28024022-9ce89866-65a0-11e7-9850-ecf6091f7e7a.jpg)

**Comment by Lichery** [comment]
я хз что это за мобы, по базе даже нет таких. Может там на кроносе что-то свое дорисовали?
