### ISSUE TITLE
Светящийся осколок, цель задания

### ISSUE THREAD

**Issue by FTNonsense** [Lichery/Server_Translation_issues#36]
тут не переведено
![3](https://user-images.githubusercontent.com/29949340/28096340-1b2bd350-66b9-11e7-8b38-59e1b60aa3ef.jpg)
а тут переведено)))
![33](https://user-images.githubusercontent.com/29949340/28096343-1f942c62-66b9-11e7-9a01-c94d38f3e550.jpg)

**Comment by Lichery** [comment]
исправил
