### ISSUE TITLE
Книга Ура

### ISSUE THREAD

**Issue by FTNonsense** [Lichery/Server_Translation_issues#42]
не переводит первые две страницы, а остальное переводит
![wow 2017-07-12 06-14-06-284](https://user-images.githubusercontent.com/29949340/28101336-f434af86-66d8-11e7-9012-d65bc13a9ef2.jpg)
![wow 2017-07-12 06-14-07-896](https://user-images.githubusercontent.com/29949340/28101335-f431eaa8-66d8-11e7-8c4f-d37db7efdf47.jpg)
![wow 2017-07-12 06-15-55-573](https://user-images.githubusercontent.com/29949340/28101334-f42e5258-66d8-11e7-8bfa-81cd07713f80.jpg)

**Comment by Lichery** [comment]
Исправил
