### ISSUE TITLE
Вехена, пожертвование - шерсть

### ISSUE THREAD

**Issue by FTNonsense** [Lichery/Server_Translation_issues#47]
![wow 2017-07-13 00-32-39-517](https://user-images.githubusercontent.com/29949340/28168308-b2165c04-67ef-11e7-9e1f-99aa4a846a4e.jpg)

**Comment by FTNonsense** [comment]
А вот у тауренов все нормально
![wow 2017-07-13 00-58-18-699](https://user-images.githubusercontent.com/29949340/28168327-c737f890-67ef-11e7-85b4-7892bf7d1100.jpg)

**Comment by Lichery** [comment]
Потому что на этом кроносе через жопу тексты в заданиях сделаны. Там где не переводится тупо не хватает 1 абзаца...
