### ISSUE TITLE
Регистрационная книга Хилсбрада

### ISSUE THREAD

**Issue by FTNonsense** [Lichery/Server_Translation_issues#49]
Некорректно отображается текст
![wow 2017-07-13 20-57-14-334](https://user-images.githubusercontent.com/29949340/28181315-3e995ce8-6819-11e7-9d95-16f19b5b4d5f.jpg)
![wow 2017-07-13 20-57-30-302](https://user-images.githubusercontent.com/29949340/28181314-3e8aed84-6819-11e7-924b-d17861dc4841.jpg)
![wow 2017-07-13 20-57-57-900](https://user-images.githubusercontent.com/29949340/28181316-3eb45200-6819-11e7-920b-2cbe6fd04d66.jpg)

**Comment by Lichery** [comment]
исправил
