### ISSUE TITLE
Катавасия

### ISSUE THREAD

**Issue by FTNonsense** [Lichery/Server_Translation_issues#53]
не переведено
![s](https://user-images.githubusercontent.com/29949340/28203622-8d6e20de-688b-11e7-8f1e-fd88b5bf5b02.jpg)
![ss](https://user-images.githubusercontent.com/29949340/28203623-8d9263e0-688b-11e7-83ae-4237e7f6dd51.jpg)

**Comment by Lichery** [comment]
это опять у тебя баги,и как и с мобами хилсбрада...
