### ISSUE TITLE
Новобранец Элрет, последнее желание Марлы

### ISSUE THREAD

**Issue by FTNonsense** [Lichery/Server_Translation_issues#60]
у вас в аддоне выдает неверный текст. забыл русский вариант заскринить, ну короч на англ. текст правильный
а на русском мне выдает "они просто идиоты.. копающие себе могилы" что-то такое, поменяйте.
![wow 2017-07-26 19-42-22-861](https://user-images.githubusercontent.com/29949340/28670623-97331caa-72ea-11e7-94e6-62a86711a791.jpg)

**Comment by Lichery** [comment]
Это к Маусу
