### ISSUE TITLE
Аукцион

### ISSUE THREAD

**Issue by FTNonsense** [Lichery/Server_Translation_issues#70]
странный баг. почему-то именно этот предмет с аукциона не перевело. в чем ошибка? может еще есть?
разбирайтесь.)
![wow 2017-08-05 22-24-57-671](https://user-images.githubusercontent.com/29949340/29012824-710caf24-7b4f-11e7-8c51-d14cbdc86bb6.jpg)

**Comment by Lichery** [comment]
потому что там предмет с бонусом и это пока вообще не работает.

**Comment by Lichery** [comment]
Реализовано
